// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Recorder {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("DetailsViewController")]
	public partial class DetailsViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_deleteButton;
		
		private MonoTouch.UIKit.UILabel __mt_lengthLabel;
		
		private MonoTouch.UIKit.UIButton __mt_playButton;
		
		private MonoTouch.UIKit.UIButton __mt_sendButton;
		
		private MonoTouch.UIKit.UILabel __mt_sizeLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("deleteButton")]
		private MonoTouch.UIKit.UIButton deleteButton {
			get {
				this.__mt_deleteButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("deleteButton")));
				return this.__mt_deleteButton;
			}
			set {
				this.__mt_deleteButton = value;
				this.SetNativeField("deleteButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lengthLabel")]
		private MonoTouch.UIKit.UILabel lengthLabel {
			get {
				this.__mt_lengthLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lengthLabel")));
				return this.__mt_lengthLabel;
			}
			set {
				this.__mt_lengthLabel = value;
				this.SetNativeField("lengthLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("playButton")]
		private MonoTouch.UIKit.UIButton playButton {
			get {
				this.__mt_playButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("playButton")));
				return this.__mt_playButton;
			}
			set {
				this.__mt_playButton = value;
				this.SetNativeField("playButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("sendButton")]
		private MonoTouch.UIKit.UIButton sendButton {
			get {
				this.__mt_sendButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("sendButton")));
				return this.__mt_sendButton;
			}
			set {
				this.__mt_sendButton = value;
				this.SetNativeField("sendButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("sizeLabel")]
		private MonoTouch.UIKit.UILabel sizeLabel {
			get {
				this.__mt_sizeLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("sizeLabel")));
				return this.__mt_sizeLabel;
			}
			set {
				this.__mt_sizeLabel = value;
				this.SetNativeField("sizeLabel", value);
			}
		}
	}
}
