// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Recorder {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UITabBarController __mt_tabBarController;
		
		private MonoTouch.UIKit.UIButton __mt_recordButton;
		
		private MonoTouch.UIKit.UIActivityIndicatorView __mt_recordIndicator;
		
		private MonoTouch.UIKit.UIProgressView __mt_recordMeter;
		
		private MonoTouch.UIKit.UILabel __mt_timeLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tabBarController")]
		private MonoTouch.UIKit.UITabBarController tabBarController {
			get {
				this.__mt_tabBarController = ((MonoTouch.UIKit.UITabBarController)(this.GetNativeField("tabBarController")));
				return this.__mt_tabBarController;
			}
			set {
				this.__mt_tabBarController = value;
				this.SetNativeField("tabBarController", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("recordButton")]
		private MonoTouch.UIKit.UIButton recordButton {
			get {
				this.__mt_recordButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("recordButton")));
				return this.__mt_recordButton;
			}
			set {
				this.__mt_recordButton = value;
				this.SetNativeField("recordButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("recordIndicator")]
		private MonoTouch.UIKit.UIActivityIndicatorView recordIndicator {
			get {
				this.__mt_recordIndicator = ((MonoTouch.UIKit.UIActivityIndicatorView)(this.GetNativeField("recordIndicator")));
				return this.__mt_recordIndicator;
			}
			set {
				this.__mt_recordIndicator = value;
				this.SetNativeField("recordIndicator", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("recordMeter")]
		private MonoTouch.UIKit.UIProgressView recordMeter {
			get {
				this.__mt_recordMeter = ((MonoTouch.UIKit.UIProgressView)(this.GetNativeField("recordMeter")));
				return this.__mt_recordMeter;
			}
			set {
				this.__mt_recordMeter = value;
				this.SetNativeField("recordMeter", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("timeLabel")]
		private MonoTouch.UIKit.UILabel timeLabel {
			get {
				this.__mt_timeLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("timeLabel")));
				return this.__mt_timeLabel;
			}
			set {
				this.__mt_timeLabel = value;
				this.SetNativeField("timeLabel", value);
			}
		}
	}
}
